def on_forever():
    basic.show_number(0)
    basic.pause(1000)
    basic.show_number(7)
    basic.pause(1000)
    basic.show_number(2)
    basic.pause(1000)
    basic.show_number(7)
    basic.pause(1000)
basic.forever(on_forever)
